### ISSUE TITLE
Toad oils and Tools randomly not working

### ISSUE THREAD

**Issue by SliferSand** [HitsparkInteractive/NinOnline#2]
## Problem description

 While fighting, tools such as kunai and shuriken, and toad oils will randomly not work. I have only seen this happen while many people are fighting at once. It's happened a lot during village raids, and most recently right now in a fun ffa in sand village guard duty map. My tools randomly would not come out, but it will still count as losing 1 tool. My oils will cast, but they won't heal and will count as losing 1 oil. I don't have a recording, but it literally is just as it sounds. Nothing special. The tools do not come out, they do not show flying through the air, and they do not deal damage where they would've hit. The oil cast bar will fill up and just nothing will happen. No marker in the top right, no sound, nothing.

## Steps to reproduce issue

Have 10 or so ninja fighting on a map intensely while trying to use tools and toad oils. It is not guaranteed. It happens randomly. I'm not sure if it has something to do with how many assets are on the map at a given time, or something else. 

I know that it says this has to be reliably reproduced, but that is just unfortunately not the case with whatever this bug is. It IS by nature random, and it affects other players as well. We are not being lazy, there just literally is no concrete way to reproduce it 100% of the time. The only thing I know is having big group fights sometimes triggers the tools and oils to not work randomly. I mean when I'm completely alone standing still, the oils do not finish. I'm not cancelling the cast, and I'm not being interrupted. Not that they stop working each time, it just becomes a coin flip on whether or not it will work.

1. Have a large group of ninja
2. Have them fight intensely
3. Try to use tools and toad oils during the fight

## Observed result

 They tools and oils will work or not work.

## Expected result

 The tools and oils to work every single time they are used unless they are cancelled by the player or an enemy. 

## More details

**Affected Client Version:**  Newest updated version as of 7/10/2021

 I remember this being an issue on the old client as well.

**First noticed:** 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
I believe that this is fixed on the next update, so will be reviewing it again then.

**Comment by RorySoh** [comment]
Hi there, the update is now out, can you see if it has improved since then?

**Comment by SliferSand** [comment]
It is still happening. Just now Leaf raided takumi, so there was lots of fighting going on and my toad oil didn't do anything. I stood still all the way on the right away from everyone. I've also had the tools issue still in the big ffa events. Oddly enough, after like five or so blank shuriken, I'd type that my tools aren't working, and then after saying that they would work. It sounds like a troll, but like that is just what happened. I don't know why. #2 

> Hi there, the update is now out, can you see if it has improved since then?
