### ISSUE TITLE
Cast time Jutsu do not cast upon entering a map

### ISSUE THREAD

**Issue by SliferSand** [HitsparkInteractive/NinOnline#69]
## Problem description

 Upon entering a map, if you cast a jutsu that requires a cast time (such as cloak of invisibility or great fireball) the entire cast bar will fill, but nothing will happen. You essentially stand there for nothing. There is a window of time this happens though. It's about 1 second. So that is to say, you can take a few steps into the new map, and cast your jutsu then, and it will just fill up with nothing happening.  

## Steps to reproduce issue

1. Enter a map
2. Use a jutsu that requires a cast time
3. Observe nothing happening

## Observed result

 The cast bar will fill up, but no jutsu will be used. 

## Expected result

 The jutsu to be used as normal

## More details
 Your character doesn't make the animation of casting a jutsu either, and it doesn't make the sound of casting a jutsu. 

**Affected Client Version:**  Most recent update

 This was happening for very early version of Inochi, but I can't recall if it was an issue before as well. 

**First noticed:**  

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
This doesn't seem to happen in the latest version. Might have been fixed with another bug report.

**Comment by SliferSand** [comment]
@RorySoh It definitely still happens I can record it if you want.
